yarnPath: .yarn/releases/yarn-3.3.0.cjs
packageExtensions:
  "@react-aria/dialog@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@react-aria/gridlist@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@react-spectrum/contextualhelp@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@react-spectrum/button@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@react-spectrum/checkbox@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@react-spectrum/label@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@react-spectrum/buttongroup@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@react-spectrum/labeledvalue@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@react-spectrum/radio@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@react-spectrum/searchfield@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@react-spectrum/textfield@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@react-spectrum/switch@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@react-spectrum/dnd@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@spectrum-icons/ui@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@spectrum-icons/workflow@*":
    peerDependenciesMeta:
      "react-dom":
        optional: true
  "@types/mini-css-extract-plugin@*":
    peerDependencies:
      "webpack": "*"
  "@types/webpack-dev-server@*":
    peerDependencies:
      "webpack": "*"
