yarnPath: .yarn/releases/yarn-3.3.0.cjs
packageExtensions:
  '@react-aria/dialog@*':
    peerDependenciesMeta:
      'react-dom':
        optional: true
  '@react-aria/gridlist@*':
    peerDependenciesMeta:
      'react-dom':
        optional: true
  '@types/mini-css-extract-plugin@*':
    peerDependencies:
      'webpack': '*'
  '@types/webpack-dev-server@*':
    peerDependencies:
      'webpack': '*'
